baseURL = 'https://noobygames.de/'
languageCode = 'de-de'
title = 'NoobyGames'
DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
menu = ['main', 'footer']
disqusShortname = 'Nerzal'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "#e4f1fe"
  author = "Tobias Theel"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "background-dark"
  recent_posts_number = 3
  custom_css = ["styles.css", "timeline.css"]

 
[params.footer]
    enable_menu_footer_primary = true
    footer_primary_menu_title = "Impressum"

[[params.socials]]
  name = "twitter"
  url = "https://twitter.com/Noobygames"


[[params.socials]]
  name = "mastodon"
  url = "https://mastodon.lol/@nerzal"

[[params.socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tobias-theel-3353a9181"

[[params.socials]]
  name = "github"
  url = "https://github.com/Nerzal"


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
